---

# Gateway config
- name: "Check if gateway is configured on {{ interface.name }}"
  command: egrep '^GATEWAY=' "{{ rhnetwork_scriptsLocation }}{{ interface.name }}"
  register: gateway_configured_result
  failed_when: false
  changed_when: false
  
- when: gateway_configured_result.rc == 0
  block:
    - name: "Check if gateway configuration is correct on {{ interface.name }}"
      command: egrep '^GATEWAY={{ interface.gateway }}$' "{{ rhnetwork_scriptsLocation }}{{ interface.name }}"
      register: gateway_correct_result
      failed_when: false
      changed_when: false

    - name: "Change configured gateway on {{ interface.name }}"
      replace:
        path: "{{ rhnetwork_scriptsLocation }}{{ interface.name }}"
        regexp: '(^GATEWAY=)(.*)$'
        replace: '\g<1>{{ interface.gateway }}'
      when: gateway_correct_result.rc == 1

- name: "Configure new gateway on {{ interface.name }}"
  lineinfile:
    path: "{{ rhnetwork_scriptsLocation }}{{ interface.name }}"
    line: "GATEWAY={{ interface.gateway }}"
  when: gateway_configured_result.rc == 1
